Shops = {}

Shops.Keys = {
    ["ESC"] = 322, ["F1"] = 288, ["F2"] = 289, ["F3"] = 170, ["F5"] = 166, ["F6"] = 167, ["F7"] = 168, ["F8"] = 169, ["F9"] = 56, ["F10"] = 57, 
    ["~"] = 243, ["1"] = 157, ["2"] = 158, ["3"] = 160, ["4"] = 164, ["5"] = 165, ["6"] = 159, ["7"] = 161, ["8"] = 162, ["9"] = 163, ["-"] = 84, ["="] = 83, ["BACKSPACE"] = 177, 
    ["TAB"] = 37, ["Q"] = 44, ["W"] = 32, ["E"] = 38, ["R"] = 45, ["T"] = 245, ["Y"] = 246, ["U"] = 303, ["P"] = 199, ["["] = 39, ["]"] = 40, ["ENTER"] = 18,
    ["CAPS"] = 137, ["A"] = 34, ["S"] = 8, ["D"] = 9, ["F"] = 23, ["G"] = 47, ["H"] = 74, ["K"] = 311, ["L"] = 182,
    ["LEFTSHIFT"] = 21, ["Z"] = 20, ["X"] = 73, ["C"] = 26, ["V"] = 0, ["B"] = 29, ["N"] = 249, ["M"] = 244, [","] = 82, ["."] = 81,
    ["LEFTCTRL"] = 36, ["LEFTALT"] = 19, ["SPACE"] = 22, ["RIGHTCTRL"] = 70, 
    ["HOME"] = 213, ["PAGEUP"] = 10, ["PAGEDOWN"] = 11, ["DELETE"] = 178,
    ["LEFT"] = 174, ["RIGHT"] = 175, ["TOP"] = 27, ["DOWN"] = 173,
    ["NENTER"] = 201, ["N4"] = 108, ["N5"] = 60, ["N6"] = 107, ["N+"] = 96, ["N-"] = 97, ["N7"] = 117, ["N8"] = 61, ["N9"] = 118
}

Shops.Products = {
    ["normal"] = {
        [1] = {
            name = "toast",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "water_bottle",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "cocacola",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "twerks_candy",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "snikkel_candy",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "sandwich",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "beer",
            price = 10,
            amount = 200,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "whiskey",
            price = 25,
            amount = 200,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "vodka",
            price = 25,
            amount = 200,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "bandage",
            price = 15,
            amount = 250,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "lighter",
            price = 100,
            amount = 200,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "walkstick",
            price = 100,
            amount = 200,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "rolling_paper",
            price = 1,
            amount = 5000,
            info = {},
            type = "item",
            slot = 13,
        },
    },
--[[    ["casino"] = {
        [1] = {
            name = "coffee",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "twerks_candy",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "snikkel_candy",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 3,
        },  
        [4] = {
            name = "beer",
            price = 10,
            amount = 200,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "whiskey",
            price = 25,
            amount = 200,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "vodka",
            price = 25,
            amount = 200,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "lighter",
            price = 100,
            amount = 200,
            info = {},
            type = "item",
            slot = 7,
        },
    },
    ["casinohb"] = {
        [1] = {
            name = "casinochips",
            price = 1,
            amount = 100000000,
            info = {},
            type = "item",
            slot = 1,
        }
    },--]]
    ["hardware"] = {
        [1] = {
            name = "phone",
            price = 400,
            amount = 200,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "binoculars",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "fitbit",
            price = 100,
            amount = 150,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "cleaningkit",
            price = 350,
            amount = 150,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "weapon_crowbar",
            price = 2000,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "firework1",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "firework2",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "firework3",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "parachute",
            price = 250,
            amount = 10,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "binoculars",
            price = 300,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },    
        [11] = {
            name = "diving_gear",
            price = 1500,
            amount = 10,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "weapon_petrolcan",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "fishingrod",
            price = 250,
            amount = 300,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "fishingbait",
            price = 50,
            amount = 300,
            info = {},
            type = "item",
            slot = 14,
        },
    },   
    ["gsgasoline"] = {
        [1] = {
            name = "toast",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "water_bottle",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "cocacola",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "twerks_candy",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "snikkel_candy",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "sandwich",
            price = 5,
            amount = 200,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "beer",
            price = 10,
            amount = 200,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "whiskey",
            price = 25,
            amount = 200,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "vodka",
            price = 25,
            amount = 200,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "bandage",
            price = 15,
            amount = 250,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "lighter",
            price = 100,
            amount = 200,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "walkstick",
            price = 100,
            amount = 200,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "rolling_paper",
            price = 1,
            amount = 5000,
            info = {},
            type = "item",
            slot = 13,
        },
    },
    ["coffeeshop"] = {
        [1] = {
            name = "weed_nutrition",
            price = 25,
            amount = 1000,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "hqscale",
            price = 500,
            amount = 10,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "empty_weed_bag",
            price = 2,
            amount = 1000,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "rolling_paper",
            price = 2,
            amount = 1000,
            info = {},
            type = "item",
            slot = 4,
        },
    },     
    ["weapons"] = {
        [1] = {
            name = "weapon_fireextinguisher",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "armor",
            price = 150,
            amount = 100,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "heavyarmor",
            price = 250,
            amount = 100,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "pistol_ammo",
            price = 25,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
    },
}

Shops.Locations = {
    --[[["casinohb"] = {
    
        ["label"] = "Casino",
        ["type"] = "lanone",
        ["coords"] = {
            [1] = {
                ["x"] = 961.31707763672, 
                ["y"] = 26.48101234436, 
                ["z"] = 76.991325378418
            },
            [2] = {
                ["x"] = 958.93334960938, 
                ["y"] = 22.576301574707, 
                ["z"] = 76.991325378418
            }
        },
        ["products"] = Shops.Products["casinohb"],
    },
    ["casino"] = {
        ["label"] = "Casino Shop",
        ["type"] = "lanone",
        ["coords"] = {
            [1] = {
                ["x"] = 970.96075439453, 
                ["y"] = 49.544052124023, 
                ["z"] = 74.991333007813
            },
            [2] = {
                ["x"] = 958.13330078125, 
                ["y"] = 57.327659606934, 
                ["z"] = 74.991333007813
            }
        },
        ["products"] = Shops.Products["casino"],
    },]]--
    ["gsgasoline"] = {
        ["label"] = "Grove Street Gasoline",
        ["type"] = "gsgasoline",
        ["coords"] = vector3(-48.42, -1757.985, 29.420997),
        ["products"] = Shops.Products["gsgasoline"],
    },
    ["robsliquor"] = {
        ["label"] = "Rob's Liqour",
        ["type"] = "normal",
        ["coords"] = vector3(-1222.77, -907.19, 12.32),
        ["products"] = Shops.Products["normal"],
    },
    ["ltdgasoline2"] = {
        ["label"] = "LTD Gasoline",
        ["type"] = "normal",
        ["coords"] = vector3(-707.41, -912.83, 19.21),
        ["products"] = Shops.Products["normal"],
    },
    ["robsliquor2"] = {
        ["label"] = "Rob's Liqour",
        ["type"] = "normal",
        ["coords"] = vector3(-1487.7, -378.53, 40.16),
        ["products"] = Shops.Products["normal"],
    },
    ["ltdgasoline3"] = {
        ["label"] = "LTD Gasoline",
        ["type"] = "normal",
        ["coords"] = vector3(-1820.33, 792.66, 138.1),
        ["products"] = Shops.Products["normal"],
    },
    ["robsliquor3"] = {
        ["label"] = "Rob's Liqour",
        ["type"] = "normal",
        ["coords"] = vector3(-2967.79, 391.64, 15.04),
        ["products"] = Shops.Products["normal"],
    },
    ["247supermarket2"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = vector3(-3038.71, 585.9, 7.9),
        ["products"] = Shops.Products["normal"],
    },
    ["247supermarket3"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = vector3(-3241.47, 1001.14, 12.83),
        ["products"] = Shops.Products["normal"],
    },
    ["247supermarket4"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = vector3(1728.66, 6414.16, 35.03),
        ["products"] = Shops.Products["normal"],
    },
    ["247supermarket5"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = vector3(1697.99, 4924.4, 42.06),
        ["products"] = Shops.Products["normal"],
    },
    ["247supermarket6"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = vector3(1961.48, 3739.96, 32.34),
        ["products"] = Shops.Products["normal"],
    },
    ["robsliquor4"] = {
        ["label"] = "Rob's Liqour",
        ["type"] = "normal",
        ["coords"] = vector3(1165.28, 2709.4, 38.15),
        ["products"] = Shops.Products["normal"],
    },
    ["247supermarket7"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = vector3(547.79, 2671.79, 42.15),
        ["products"] = Shops.Products["normal"],
    },
    ["247supermarket8"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = vector3(2679.25, 3280.12, 55.24),
        ["products"] = Shops.Products["normal"],
    },
    ["247supermarket9"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = vector3(2557.94, 382.05, 108.62),
        ["products"] = Shops.Products["normal"],
    },
    ["delvecchioliquor"] = {
        ["label"] = "Del Vecchio Liquor",
        ["type"] = "normal",
        ["coords"] = vector3(-159.36, 6321.59, 31.58),
        ["products"] = Shops.Products["normal"],
    },
    ["donscountrystore"] = {
        ["label"] = "Don's Country Store",
        ["type"] = "normal",
        ["coords"] = vector3(161.41, 6640.78, 31.69),
        ["products"] = Shops.Products["normal"],
    },
    ["ltdgasoline4"] = {
        ["label"] = "LTD Gasoline",
        ["type"] = "normal",
        ["coords"] = vector3(1163.7, -323.92, 69.2),
        ["products"] = Shops.Products["normal"],
    },
    ["robsliquor5"] = {
        ["label"] = "Rob's Liqour",
        ["type"] = "normal",
        ["coords"] = vector3(1135.66, -982.76, 46.41),
        ["products"] = Shops.Products["normal"],
    },
    ["247supermarket10"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = vector3(373.55, 325.56, 103.56),
        ["products"] = Shops.Products["normal"],
    },
    ["247supermarket11"] = {
        ["label"] = "24/7 Supermarket",
        ["type"] = "normal",
        ["coords"] = vector3(25.715412, -1347.268, 29.49702),
        ["products"] = Shops.Products["normal"],
    },
    ["hardware"] = {
        ["label"] = "Tool Shop",
        ["type"] = "hardware",
        ["coords"] = vector3(44.83, -1748.53, 29.54),
        ["products"] = Shops.Products["hardware"],
    },
    ["hardware2"] = {
        ["label"] = "Tool Shop",
        ["type"] = "hardware",
        ["coords"] = vector3(2749.23, 3472.33, 55.67),
        ["products"] = Shops.Products["hardware"],
    }, 
    ["coffeeshop"] = {
        ["label"] = "Smoke Store",
        ["type"] = "hardware",
        ["coords"] = vector3(-1172.43, -1572.24, 4.66),
        ["products"] = Shops.Products["coffeeshop"],
    },
--[[    ["coffeelounge"] = {
        ["label"] = "Coffee Lounge",
        ["type"] = "coffeelounge",
        ["coords"] = {
            [1] = {
                ["x"] = -633.48,
                ["y"] = 235.42,
                ["z"] = 82.00,
            }
        },
        ["products"] = Shops.Products["coffeelounge"],
    },--]]
    ["ammunation1"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector3(-662.1, -935.3, 21.8),
        ["products"] = Shops.Products["weapons"],
    },
    ["ammunation2"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector3(810.2, -2157.3, 29.6),
        ["products"] = Shops.Products["weapons"],
    },
    ["ammunation3"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector3(1693.4, 3759.5, 34.7),
        ["products"] = Shops.Products["weapons"],
    },
    ["ammunation4"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector3(-330.2, 6083.8, 31.4),
        ["products"] = Shops.Products["weapons"],
    },
    ["ammunation5"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector3(252.3, -50.0, 69.9),
        ["products"] = Shops.Products["weapons"],
    },
    ["ammunation6"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector3(22.0, -1107.2, 29.8),
        ["products"] = Shops.Products["weapons"],
    },
    ["ammunation7"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector3(2567.6, 294.3, 108.7),
        ["products"] = Shops.Products["weapons"],
    },
    ["ammunation8"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector3(-1117.5, 2698.6, 18.5),
        ["products"] = Shops.Products["weapons"],
    },
    ["ammunation9"] = {
        ["label"] = "Ammunation",
        ["type"] = "weapon",
        ["coords"] = vector3(842.4, -1033.4, 28.1),
        ["products"] = Shops.Products["weapons"],
    },    
}